pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=Travis CI - Branch
      - status-success=Travis CI - Pull Request
      - status-success=continuous-integration/appveyor/pr
      - status-success=continuous-integration/appveyor/branch
      - label=auto-merge
      - author=TomoyukiAota
    actions:
      merge:
        method: merge
      delete_head_branch: {}
