pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=test (ubuntu-20.04)
      - status-success=test (windows-latest)
      - status-success=test (macOS-latest)
      - label=automerge
      - author=TomoyukiAota
    actions:
      merge:
        method: merge
      delete_head_branch: {}
