pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=CI on Ubuntu / test (ubuntu-latest) (pull_request)
      - status-success=CI on Ubuntu / test (ubuntu-latest) (push)
      - status-success=CI on Windows / test (windows-latest) (pull_request)
      - status-success=CI on Windows / test (windows-latest) (push)
      - status-success=CI on macOS / test (macOS-latest) (pull_request)
      - status-success=CI on macOS / test (macOS-latest) (push)
      - label=automerge
      - author=TomoyukiAota
    actions:
      merge:
        method: merge
      delete_head_branch: {}
