os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.2
language: node_js
node_js:
  - "12"
sudo: required
addons:
    chrome: stable
services:
  - xvfb
install:
  - npm set progress=false
  - travis_retry npm ci
script:
  - travis_retry npm run lint:ng
  - travis_retry npm run lint:es
  - travis_retry npm run test:unit:ng
  - travis_retry npm run test:unit:em:main
  - travis_retry npm run test:unit:em:renderer
  - travis_retry npm run test:e2e
  - travis_wait 40 travis_retry npm run test:package
