os:
  - linux
  - osx
language: node_js
node_js:
  - "10"
  - "11"
sudo: required
addons:
    chrome: stable
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
install:
  - npm set progress=false
  - travis_retry npm install
script:
  - travis_retry npm run lint:ng
  - travis_retry npm run lint:es
  - travis_retry npm run test:unit:karma
  - travis_retry npm run test:unit:em:main
  - travis_retry npm run test:e2e
  - travis_retry npm run test:package
