# Install scripts. (runs after repo cloning)
install:
  - dir C:\avvm\node
  - ps: Install-Product node 10
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - ng lint
  - npm run test
  - npm run e2e
  - npm run build

# Don't actually build.
build: off