environment:
  matrix:
    - nodejs_version: "12"      # Highest LTS version available in AppVeyor

platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  - choco upgrade googlechrome --ignore-checksums
  - dir C:\avvm\node            # Print available versions of Node.js in AppVeyor
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm set progress=false
  - appveyor-retry npm ci

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - appveyor-retry npm run lint:ng
  - appveyor-retry npm run lint:es
  - appveyor-retry npm run test:unit:ng
  - appveyor-retry npm run test:unit:em:main
  - appveyor-retry npm run test:unit:em:renderer
  - appveyor-retry npm run test:e2e

  # Disabled since "".\release\Photo Location Map Setup 0.0.1.exe" /S" fails for unknown reason. (My local PC is fine.)
  #  - appveyor-retry npm run test:package

  # Publish to GitHub release (To publish, GH_TOKEN environment variable needs to be set on AppVeyor.)
  - appveyor-retry git clean -fdx   # Delete files which are not registered to git before starting to create the release package.
  - appveyor-retry git clean -fdx   # Run twice to be sure of deleting files
  - appveyor-retry npm ci
  - appveyor-retry npm run publish:windows

# Don't actually build.
build: off
