name: Any Issue
description: File any issue (not necessarily a bug)
title: ""
labels: ["needs triage"]
assignees:
  - TomoyukiAota
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
    validations:
      required: true
