name: Any Issue
description: File any issue. (Use "Bug Report" to file a bug.)
labels: ["needs triage"]
assignees:
  - TomoyukiAota
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
    validations:
      required: true
