name: CI on Windows

on:
  push:
    branches:
      - '**'    # matches every branch
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [12.x]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # for electron-builder

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint:ng
    - run: npm run lint:es
    - run: npm run test:unit:ng
    - run: npm run test:unit:em:main
    - run: npm run test:unit:em:renderer
    - run: npm run test:e2e
    - run: npm run test:package

    - name: Publish to GitHub release     # To publish, GH_TOKEN environment variable needs to be set.
      run: |
        echo "Making sure files unregistered to git are deleted by running "git clean -fdx" twice..."
        git clean -fdx
        git clean -fdx
        echo "Install npm modules. Then, create and publish Windows package."
        npm ci
        npm run publish:windows
