name: CI on macOS

on:
  push:
    branches:
      - '**'    # matches every branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    # The timeout below is to bound the duration of a hung job.
    # This job once hung in "npm run test:package" and kept running for more than 40 minutes until it was cancelled manually.
    # This job takes about 20 minutes at the longest on macos-26-intel, so the timeout below has enough margin.
    timeout-minutes: 45

    strategy:
      fail-fast: false    # To see the result on both architectures even when one of them fails
      matrix:
        os: [macos-26, macos-26-intel]    # macos-26 is arm64 (Apple Silicon), and macos-26-intel is x64.

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # for electron-builder

    steps:
    - uses: actions/checkout@v7

    - name: Install Node.js with the version in mise.toml
      uses: jdx/mise-action@v4

    - name: npm ci
      run: npm ci

    - name: npm run lint:ng
      run: npm run lint:ng

    - name: npm run lint:script
      run: npm run lint:script

    - name: npm run test:unit:ng
      run: npm run test:unit:ng

    - name: npm run test:unit:em:main
      run: npm run test:unit:em:main

    - name: npm run test:unit:em:renderer
      run: npm run test:unit:em:renderer

    - name: npm run test:package
      run: npm run test:package
