name: CI on Windows

on:
  push:
    branches:
      - '**'    # matches every branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # for electron-builder

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.13.0
      uses: actions/setup-node@v1
      with:
        node-version: 18.13.0

    - name: npm ci
      run: npm ci

    - name: npm run lint:ng
      run: npm run lint:ng

    - name: npm run lint:script
      run: npm run lint:script

    - name: npm run test:unit:ng
      run: npm run test:unit:ng

    - name: npm run test:unit:em:main
      run: npm run test:unit:em:main

    - name: npm run test:unit:em:renderer
      run: npm run test:unit:em:renderer

    - name: npm run test:package
      run: npm run test:package

    - name: '[Publish to GitHub Releases] Clean-up by "git clean -fdx" (1st time)'
      run: git clean -fdx

    - name: '[Publish to GitHub Releases] Clean-up by "git clean -fdx" (2nd time to be sure)'
      run: git clean -fdx

    - name: '[Publish to GitHub Releases] npm ci'
      run: npm ci

    - name: '[Publish to GitHub Releases] Create and publish Windows package'
      uses: nick-invision/retry@v2.2.0
      with:
        timeout_minutes: 60
        max_attempts: 10
        retry_on: error
        command: npm run publish:windows      # To publish, GH_TOKEN environment variable needs to be set.
