name: CI on macOS

on:
  push:
    branches:
      - '**'    # matches every branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # for electron-builder

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.18.2
      uses: actions/setup-node@v1
      with:
        node-version: 18.18.2

    - name: npm ci
      run: npm ci

    - name: npm run lint:ng
      run: npm run lint:ng

    - name: npm run lint:script
      run: npm run lint:script

    - name: npm run test:unit:ng
      run: npm run test:unit:ng

    - name: npm run test:unit:em:main
      run: npm run test:unit:em:main

    - name: npm run test:unit:em:renderer
      run: npm run test:unit:em:renderer

    - name: npm run test:package
      run: npm run test:package
