name: CI on Ubuntu

on:
  push:
    branches:
      - '**'    # matches every branch
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # for electron-builder

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.15.1
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.1

    - name: npm ci
      run: npm ci

    - name: npm run lint:ng
      run: npm run lint:ng

    - name: npm run lint:es
      run: npm run lint:es

    - name: npm run test:unit:ng
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm run test:unit:ng

    - name: npm run test:unit:em:main
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm run test:unit:em:main

    - name: npm run test:unit:em:renderer
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm run test:unit:em:renderer

#    - name: npm run test:e2e
#      uses: GabrielBB/xvfb-action@v1.4
#      with:
#        run: npm run test:e2e

    - name: npm run test:package
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm run test:package

# Uncomment the lines below to publish Linux package to GitHub Releases.
#
#    - name: '[Publish to GitHub Releases] Clean-up by "git clean -fdx" (1st time)'
#      run: git clean -fdx
#
#    - name: '[Publish to GitHub Releases] Clean-up by "git clean -fdx" (2nd time to be sure)'
#      run: git clean -fdx
#
#    - name: '[Publish to GitHub Releases] npm ci'
#      run: npm ci
#
#    - name: '[Publish to GitHub Releases] Create and publish Linux package'
#      uses: nick-invision/retry@v2.2.0
#      with:
#        timeout_minutes: 60
#        max_attempts: 10
#        retry_on: error
#        command: npm run publish:linux      # To publish, GH_TOKEN environment variable needs to be set.
