name: CI on Ubuntu

on:
  push:
    branches:
      - '**'    # matches every branch
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # for electron-builder

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint:ng
    - run: npm run lint:es

    - name: Run "npm run test:unit:ng" with Xvfb
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm run test:unit:ng

    - name: Run "npm run test:unit:em:main" with Xvfb
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm run test:unit:em:main

    - name: Run "npm run test:unit:em:renderer" with Xvfb
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm run test:unit:em:renderer

    - name: Run "npm run test:e2e" with Xvfb
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm run test:e2e

    - name: Run "npm run test:package" with Xvfb
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm run test:package

    - name: Publish to GitHub release     # To publish, GH_TOKEN environment variable needs to be set.
      run: |
        echo "Making sure files unregistered to git are deleted by running "git clean -fdx" twice..."
        git clean -fdx
        git clean -fdx
        echo "Install npm modules. Then, create and publish Linux package."
        npm ci
        npm run publish:linux
