# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Photo Location Map CI

on:
  push:
    branches:
      - '**'    # matches every branch
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint:ng
    - run: npm run lint:es
    - run: npm run test:unit:ng
    - run: npm run test:unit:em:main
    - run: npm run test:unit:em:renderer
    - run: npm run test:e2
    - run: npm run test:package
